### ISSUE TITLE
Error in Cloudwatch when uploading files using this lambda

### ISSUE THREAD

**Issue by skolin** [braze-inc/growth-shares-lambda-user-csv-import#3]
What is the likely reason for this error, and what do you envision are your possible methods to recover from this.
[time2-error.txt](https://github.com/braze-inc/growth-shares-lambda-user-csv-import/files/7514647/time2-error.txt)

**Comment by macolko** [comment]
Hey @skolin,
The error was caused by the connection error between the application and the server. These errors were expected to be retried through the requests session, however, it seems like that error is not being retried. I will provide a solution to automatically retry these errors.

Meanwhile, you can follow instructions [here](https://github.com/braze-inc/growth-shares-lambda-user-csv-import#manual-triggers) on how you can use the event given back to you (right under the line *"Use the event below to continue processing the file:"* to continue processing from the same point in file.

**Comment by skolin** [comment]
Thanks, we'll look forward to the update.

**Comment by macolko** [comment]
The newest [release v0.1.4](https://github.com/braze-inc/growth-shares-lambda-user-csv-import/releases/tag/v.0.1.4) improves the retries. You can update the function manually with the zip file, described [here](https://github.com/braze-inc/growth-shares-lambda-user-csv-import#updating-an-existing-function). The update to the serverless repository is coming shortly.

**Comment by skolin** [comment]
Thank you, I will put it  to test .

**Comment by skolin** [comment]
Good for now
